#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Users/jones/development/gwt-mac-1.5.3/gwt-user.jar:/Users/jones/development/gwt-mac-1.5.3/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.jsc.SkaterData;
